variable azs {}     
variable private_subnets {}
variable public_subnets {} 
variable environment {}
variable region {}
variable alb-name {}   
.variable vpc_id {}
variable my_public_key_location {}
variable image {}