variable vpc_id {}  
variable my_ip {}
variable env_prefix {}
variable image_name {}
#variable my_public_key_location {}
variable instance_type {}
variable avail_zone {}
variable subnet_id {}
variable vpc_security_group_ids {}